### ISSUE TITLE
Radar Altitude position when open Stats bar

### ISSUE THREAD

**Issue by lebrnno** [DK22Pac/mobile-hud#1]
![20170619210752_1](https://user-images.githubusercontent.com/23457096/27311568-2a97246c-5538-11e7-8f33-f4cbe613dbd3.jpg)
![20170619210751_1](https://user-images.githubusercontent.com/23457096/27311570-2aaaa14a-5538-11e7-9416-a0a18644ba4f.jpg)

**Comment by gennariarmando** [comment]
Issue was fixed.
